name: Alterseko
favicon: null
layout_spectrum: 0.56727
typography_spectrum: 0.39143
title: Altersekoenterprisesltd
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#7f99cc'
    - '#6271b6'
    - '#b6dff5'
    - '#96b1dc'
  brandStrength: 0.25
  lightness: 0
  saturation: 0.8125
  rhythmicContrast: 0
purpose: []
