name: Alterseko
favicon: null
layout_spectrum: 0.74291
typography_spectrum: 0.39143
title: Altersekoenterprisesltd
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#6271b6'
    - '#7f99cc'
    - '#b7e0f6'
    - '#96b1dc'
    - '#a5cae9'
  brandStrength: 0.25
  lightness: 0.125
  saturation: 0.875
  rhythmicContrast: 0
purpose: []
