name: Alterseko
favicon: null
layout_spectrum: 1
typography_spectrum: 0.83443
title: Altersekoenterprisesltd
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#05060a'
    - '#003e67'
    - '#484f57'
    - '#8d919a'
    - '#b5bcc4'
  brandStrength: 1
  lightness: 0
  saturation: 0
  rhythmicContrast: 0.5
purpose: []
